#!/usr/bin/env bash

function bootstrap {
  local shome="${_isomorphic_clojurescript_reagent_node_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  block compile npm

  lein cljsbuild once server client
}

bootstrap
