#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  cd "$shome"
  case "${1:-}" in
    default)
      exec rlwrap lein figwheel client server
      ;;
    *)
      echo "ERROR: unknown console command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

main "$@"
