#!/usr/bin/env bash

function fresh {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ ! -f "$shome/resources/public/server/js/server.js" ]]; then
    return 1
  fi

  if ! type -P rlwrap >/dev/null; then
    return 1
  fi

  return 0
}

fresh
