#!/usr/bin/env bash

function fresh {
  local shome="${_isomorphic_clojurescript_reagent_node_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -f resources/public/js/server/server.js ]]; then
    return 0
  fi

  return 1
}

fresh
