#!/usr/bin/env bash

function fresh {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -f resources/public/js/server-side/server.js ]]; then
    return 0
  fi

  return 1
}

fresh
