#!/usr/bin/env bash

function _isomorphic_clojurescript_reagent_node_profile {
  local shome="${_isomorphic_clojurescript_reagent_node_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
}

_isomorphic_clojurescript_reagent_node_profile
