#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  case "${1:-}" in
    figwheel)
      exec lein figwheel client server
      ;;

    *)
      exec node resources/public/js/server/server.js
      ;;
  esac
}

bootstrap "$@"
